server:
  port: 9611
spring:
  datasource:
    url: jdbc:mysql://111.230.151.11:3306/springboot-flowable?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    database: mysql
  redis:
    host: 111.230.151.11
    port: 6370
    database: 14
    password: mypassword

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  check-config-location: true

flowable:
  #关闭定时任务JOB
  async-executor-activate: false

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: portal
      client-secret: huazhu

vesta:
  machine: 18